// Code generated by protoc-gen-gogo.
// source: objects.proto
// DO NOT EDIT!

/*
	Package indexer is a generated protocol buffer package.

	It is generated from these files:
		objects.proto

	It has these top-level messages:
		MetricFindItem
		MetricExpandItem
		MetricTagItem
*/
package indexer

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import repr "cadent/server/repr"
import _ "github.com/gogo/protobuf/gogoproto"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// the basic metric json blob for find
type MetricFindItem struct {
	Text          string      `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Expandable    uint32      `protobuf:"varint,2,opt,name=expandable,proto3" json:"expandable,omitempty"`
	Leaf          uint32      `protobuf:"varint,3,opt,name=leaf,proto3" json:"leaf,omitempty"`
	Path          string      `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	AllowChildren uint32      `protobuf:"varint,5,opt,name=allowChildren,proto3" json:"allowChildren,omitempty"`
	Id            string      `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	UniqueId      string      `protobuf:"bytes,7,opt,name=uniqueId,json=uniqueid,proto3" json:"uniqueId,omitempty"`
	Tags          []*repr.Tag `protobuf:"bytes,13,rep,name=tags" json:"tags,omitempty"`
	MetaTags      []*repr.Tag `protobuf:"bytes,14,rep,name=metaTags,json=meta_tags" json:"metaTags,omitempty"`
}

func (m *MetricFindItem) Reset()                    { *m = MetricFindItem{} }
func (m *MetricFindItem) String() string            { return proto.CompactTextString(m) }
func (*MetricFindItem) ProtoMessage()               {}
func (*MetricFindItem) Descriptor() ([]byte, []int) { return fileDescriptorObjects, []int{0} }

type MetricExpandItem struct {
	Results []string `protobuf:"bytes,2,rep,name=results" json:"results,omitempty"`
}

func (m *MetricExpandItem) Reset()                    { *m = MetricExpandItem{} }
func (m *MetricExpandItem) String() string            { return proto.CompactTextString(m) }
func (*MetricExpandItem) ProtoMessage()               {}
func (*MetricExpandItem) Descriptor() ([]byte, []int) { return fileDescriptorObjects, []int{1} }

type MetricTagItem struct {
	Id     string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name   string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Value  string `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	IsMeta bool   `protobuf:"varint,5,opt,name=isMeta,json=is_meta,proto3" json:"isMeta,omitempty"`
}

func (m *MetricTagItem) Reset()                    { *m = MetricTagItem{} }
func (m *MetricTagItem) String() string            { return proto.CompactTextString(m) }
func (*MetricTagItem) ProtoMessage()               {}
func (*MetricTagItem) Descriptor() ([]byte, []int) { return fileDescriptorObjects, []int{2} }

func init() {
	proto.RegisterType((*MetricFindItem)(nil), "indexer.MetricFindItem")
	proto.RegisterType((*MetricExpandItem)(nil), "indexer.MetricExpandItem")
	proto.RegisterType((*MetricTagItem)(nil), "indexer.MetricTagItem")
}
func (m *MetricFindItem) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *MetricFindItem) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Text) > 0 {
		data[i] = 0xa
		i++
		i = encodeVarintObjects(data, i, uint64(len(m.Text)))
		i += copy(data[i:], m.Text)
	}
	if m.Expandable != 0 {
		data[i] = 0x10
		i++
		i = encodeVarintObjects(data, i, uint64(m.Expandable))
	}
	if m.Leaf != 0 {
		data[i] = 0x18
		i++
		i = encodeVarintObjects(data, i, uint64(m.Leaf))
	}
	if len(m.Path) > 0 {
		data[i] = 0x22
		i++
		i = encodeVarintObjects(data, i, uint64(len(m.Path)))
		i += copy(data[i:], m.Path)
	}
	if m.AllowChildren != 0 {
		data[i] = 0x28
		i++
		i = encodeVarintObjects(data, i, uint64(m.AllowChildren))
	}
	if len(m.Id) > 0 {
		data[i] = 0x32
		i++
		i = encodeVarintObjects(data, i, uint64(len(m.Id)))
		i += copy(data[i:], m.Id)
	}
	if len(m.UniqueId) > 0 {
		data[i] = 0x3a
		i++
		i = encodeVarintObjects(data, i, uint64(len(m.UniqueId)))
		i += copy(data[i:], m.UniqueId)
	}
	if len(m.Tags) > 0 {
		for _, msg := range m.Tags {
			data[i] = 0x6a
			i++
			i = encodeVarintObjects(data, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(data[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.MetaTags) > 0 {
		for _, msg := range m.MetaTags {
			data[i] = 0x72
			i++
			i = encodeVarintObjects(data, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(data[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *MetricExpandItem) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *MetricExpandItem) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Results) > 0 {
		for _, s := range m.Results {
			data[i] = 0x12
			i++
			l = len(s)
			for l >= 1<<7 {
				data[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			data[i] = uint8(l)
			i++
			i += copy(data[i:], s)
		}
	}
	return i, nil
}

func (m *MetricTagItem) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *MetricTagItem) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		data[i] = 0x12
		i++
		i = encodeVarintObjects(data, i, uint64(len(m.Id)))
		i += copy(data[i:], m.Id)
	}
	if len(m.Name) > 0 {
		data[i] = 0x1a
		i++
		i = encodeVarintObjects(data, i, uint64(len(m.Name)))
		i += copy(data[i:], m.Name)
	}
	if len(m.Value) > 0 {
		data[i] = 0x22
		i++
		i = encodeVarintObjects(data, i, uint64(len(m.Value)))
		i += copy(data[i:], m.Value)
	}
	if m.IsMeta {
		data[i] = 0x28
		i++
		if m.IsMeta {
			data[i] = 1
		} else {
			data[i] = 0
		}
		i++
	}
	return i, nil
}

func encodeFixed64Objects(data []byte, offset int, v uint64) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	data[offset+4] = uint8(v >> 32)
	data[offset+5] = uint8(v >> 40)
	data[offset+6] = uint8(v >> 48)
	data[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Objects(data []byte, offset int, v uint32) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintObjects(data []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		data[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	data[offset] = uint8(v)
	return offset + 1
}
func NewPopulatedMetricFindItem(r randyObjects, easy bool) *MetricFindItem {
	this := &MetricFindItem{}
	this.Text = randStringObjects(r)
	this.Expandable = uint32(r.Uint32())
	this.Leaf = uint32(r.Uint32())
	this.Path = randStringObjects(r)
	this.AllowChildren = uint32(r.Uint32())
	this.Id = randStringObjects(r)
	this.UniqueId = randStringObjects(r)
	if r.Intn(10) != 0 {
		v1 := r.Intn(5)
		this.Tags = make([]*repr.Tag, v1)
		for i := 0; i < v1; i++ {
			this.Tags[i] = repr.NewPopulatedTag(r, easy)
		}
	}
	if r.Intn(10) != 0 {
		v2 := r.Intn(5)
		this.MetaTags = make([]*repr.Tag, v2)
		for i := 0; i < v2; i++ {
			this.MetaTags[i] = repr.NewPopulatedTag(r, easy)
		}
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedMetricExpandItem(r randyObjects, easy bool) *MetricExpandItem {
	this := &MetricExpandItem{}
	v3 := r.Intn(10)
	this.Results = make([]string, v3)
	for i := 0; i < v3; i++ {
		this.Results[i] = randStringObjects(r)
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedMetricTagItem(r randyObjects, easy bool) *MetricTagItem {
	this := &MetricTagItem{}
	this.Id = randStringObjects(r)
	this.Name = randStringObjects(r)
	this.Value = randStringObjects(r)
	this.IsMeta = bool(bool(r.Intn(2) == 0))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

type randyObjects interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneObjects(r randyObjects) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringObjects(r randyObjects) string {
	v4 := r.Intn(100)
	tmps := make([]rune, v4)
	for i := 0; i < v4; i++ {
		tmps[i] = randUTF8RuneObjects(r)
	}
	return string(tmps)
}
func randUnrecognizedObjects(r randyObjects, maxFieldNumber int) (data []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		data = randFieldObjects(data, r, fieldNumber, wire)
	}
	return data
}
func randFieldObjects(data []byte, r randyObjects, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		data = encodeVarintPopulateObjects(data, uint64(key))
		v5 := r.Int63()
		if r.Intn(2) == 0 {
			v5 *= -1
		}
		data = encodeVarintPopulateObjects(data, uint64(v5))
	case 1:
		data = encodeVarintPopulateObjects(data, uint64(key))
		data = append(data, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		data = encodeVarintPopulateObjects(data, uint64(key))
		ll := r.Intn(100)
		data = encodeVarintPopulateObjects(data, uint64(ll))
		for j := 0; j < ll; j++ {
			data = append(data, byte(r.Intn(256)))
		}
	default:
		data = encodeVarintPopulateObjects(data, uint64(key))
		data = append(data, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return data
}
func encodeVarintPopulateObjects(data []byte, v uint64) []byte {
	for v >= 1<<7 {
		data = append(data, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	data = append(data, uint8(v))
	return data
}
func (m *MetricFindItem) Size() (n int) {
	var l int
	_ = l
	l = len(m.Text)
	if l > 0 {
		n += 1 + l + sovObjects(uint64(l))
	}
	if m.Expandable != 0 {
		n += 1 + sovObjects(uint64(m.Expandable))
	}
	if m.Leaf != 0 {
		n += 1 + sovObjects(uint64(m.Leaf))
	}
	l = len(m.Path)
	if l > 0 {
		n += 1 + l + sovObjects(uint64(l))
	}
	if m.AllowChildren != 0 {
		n += 1 + sovObjects(uint64(m.AllowChildren))
	}
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovObjects(uint64(l))
	}
	l = len(m.UniqueId)
	if l > 0 {
		n += 1 + l + sovObjects(uint64(l))
	}
	if len(m.Tags) > 0 {
		for _, e := range m.Tags {
			l = e.Size()
			n += 1 + l + sovObjects(uint64(l))
		}
	}
	if len(m.MetaTags) > 0 {
		for _, e := range m.MetaTags {
			l = e.Size()
			n += 1 + l + sovObjects(uint64(l))
		}
	}
	return n
}

func (m *MetricExpandItem) Size() (n int) {
	var l int
	_ = l
	if len(m.Results) > 0 {
		for _, s := range m.Results {
			l = len(s)
			n += 1 + l + sovObjects(uint64(l))
		}
	}
	return n
}

func (m *MetricTagItem) Size() (n int) {
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovObjects(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovObjects(uint64(l))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovObjects(uint64(l))
	}
	if m.IsMeta {
		n += 2
	}
	return n
}

func sovObjects(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozObjects(x uint64) (n int) {
	return sovObjects(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MetricFindItem) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowObjects
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MetricFindItem: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MetricFindItem: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Text", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowObjects
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthObjects
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Text = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Expandable", wireType)
			}
			m.Expandable = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowObjects
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Expandable |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Leaf", wireType)
			}
			m.Leaf = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowObjects
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Leaf |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Path", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowObjects
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthObjects
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Path = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowChildren", wireType)
			}
			m.AllowChildren = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowObjects
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.AllowChildren |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowObjects
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthObjects
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UniqueId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowObjects
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthObjects
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UniqueId = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tags", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowObjects
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthObjects
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tags = append(m.Tags, &repr.Tag{})
			if err := m.Tags[len(m.Tags)-1].Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetaTags", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowObjects
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthObjects
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MetaTags = append(m.MetaTags, &repr.Tag{})
			if err := m.MetaTags[len(m.MetaTags)-1].Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipObjects(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthObjects
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MetricExpandItem) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowObjects
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MetricExpandItem: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MetricExpandItem: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Results", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowObjects
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthObjects
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Results = append(m.Results, string(data[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipObjects(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthObjects
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MetricTagItem) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowObjects
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MetricTagItem: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MetricTagItem: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowObjects
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthObjects
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowObjects
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthObjects
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowObjects
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthObjects
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsMeta", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowObjects
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsMeta = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipObjects(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthObjects
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipObjects(data []byte) (n int, err error) {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowObjects
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowObjects
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if data[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowObjects
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthObjects
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowObjects
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := data[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipObjects(data[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthObjects = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowObjects   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("objects.proto", fileDescriptorObjects) }

var fileDescriptorObjects = []byte{
	// 382 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x5c, 0x51, 0xcd, 0x6a, 0xdb, 0x40,
	0x10, 0xb6, 0xe4, 0x1f, 0xd9, 0x5b, 0x64, 0xca, 0x52, 0xe8, 0x62, 0x6a, 0x61, 0x4c, 0x29, 0x3e,
	0xb4, 0x16, 0xb4, 0x6f, 0xd0, 0xd2, 0x82, 0x0f, 0xbd, 0x08, 0xdf, 0xcd, 0x4a, 0x1a, 0xcb, 0x5b,
	0xf4, 0xd7, 0xd5, 0xca, 0xf1, 0x0b, 0xe4, 0x9e, 0x47, 0xca, 0xd1, 0xc7, 0x3c, 0x42, 0x9c, 0xbc,
	0x44, 0x8e, 0xd9, 0x9d, 0x75, 0x42, 0x92, 0xc3, 0x88, 0x6f, 0xbe, 0xf9, 0x66, 0x76, 0xe6, 0x13,
	0xf1, 0xab, 0xf8, 0x1f, 0x24, 0xaa, 0x59, 0xd6, 0xb2, 0x52, 0x15, 0xf5, 0x44, 0x99, 0xc2, 0x01,
	0xe4, 0x64, 0x9a, 0xf0, 0x14, 0x4a, 0x15, 0x36, 0x20, 0xf7, 0x20, 0x43, 0x09, 0xb5, 0xfd, 0x58,
	0xdd, 0xe4, 0x5b, 0x26, 0xd4, 0xae, 0x8d, 0x97, 0x49, 0x55, 0x84, 0x59, 0x95, 0x55, 0x21, 0xd2,
	0x71, 0xbb, 0xc5, 0x0c, 0x13, 0x44, 0x56, 0x3e, 0xbf, 0x74, 0xc9, 0xf8, 0x2f, 0x28, 0x29, 0x92,
	0x3f, 0xfa, 0x81, 0x95, 0x82, 0x82, 0x52, 0xd2, 0x53, 0x70, 0x50, 0xcc, 0x99, 0x39, 0x8b, 0x51,
	0x84, 0x98, 0x06, 0x84, 0xc0, 0xa1, 0xe6, 0x65, 0xca, 0xe3, 0x1c, 0x98, 0xab, 0x2b, 0x7e, 0xf4,
	0x82, 0x31, 0x3d, 0x39, 0xf0, 0x2d, 0xeb, 0x62, 0x05, 0xb1, 0xe1, 0x6a, 0xae, 0x76, 0xac, 0x67,
	0xe7, 0x18, 0x4c, 0x3f, 0x13, 0x9f, 0xe7, 0x79, 0x75, 0xf1, 0x6b, 0x27, 0xf2, 0x54, 0x42, 0xc9,
	0xfa, 0xd8, 0xf0, 0x9a, 0xa4, 0x63, 0xe2, 0x8a, 0x94, 0x0d, 0xb0, 0x4f, 0x23, 0x3a, 0x21, 0xc3,
	0xb6, 0x14, 0xff, 0x5b, 0x58, 0xa5, 0xcc, 0x43, 0xf6, 0x9c, 0xeb, 0xda, 0x54, 0x6f, 0xcb, 0xb3,
	0x86, 0xf9, 0xb3, 0xee, 0xe2, 0xdd, 0xf7, 0xd1, 0x12, 0xad, 0x58, 0xf3, 0x2c, 0x42, 0x9a, 0x7e,
	0x21, 0xc3, 0x02, 0x14, 0x5f, 0x1b, 0xc9, 0xf8, 0xad, 0x64, 0x64, 0x4a, 0x1b, 0xa3, 0x9b, 0x7f,
	0x25, 0xef, 0xad, 0x0d, 0xbf, 0xf1, 0x28, 0x34, 0x82, 0x11, 0x4f, 0x42, 0xd3, 0xe6, 0xaa, 0xd1,
	0x17, 0x77, 0xf5, 0xab, 0x4f, 0xe9, 0x3c, 0x26, 0xbe, 0x55, 0xeb, 0x29, 0x28, 0xb5, 0x1b, 0xbb,
	0xcf, 0x1b, 0xeb, 0xdb, 0x4b, 0x5e, 0x00, 0xfa, 0xa1, 0x6f, 0x37, 0x98, 0x7e, 0x20, 0xfd, 0x3d,
	0xcf, 0x5b, 0x38, 0x1b, 0x62, 0x13, 0xfa, 0x91, 0x0c, 0x44, 0xa3, 0x87, 0x71, 0xb4, 0x62, 0x18,
	0x79, 0xa2, 0xd9, 0x98, 0xb5, 0x7e, 0x7e, 0x3a, 0x9e, 0x82, 0xce, 0xc3, 0x29, 0x70, 0xae, 0xef,
	0x02, 0xe7, 0xa8, 0xe3, 0x46, 0xc7, 0xad, 0x8e, 0xab, 0xfb, 0xa0, 0x13, 0x0f, 0xf0, 0xf7, 0xfd,
	0x78, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x10, 0xa7, 0xa2, 0x0f, 0x26, 0x02, 0x00, 0x00,
}
