version: '2'
volumes:
    cadent-data:
        driver: local

services:
    graphite:
        build:
            context: .
            dockerfile: docker/graphite.docker
        working_dir: /opt/graphite

        environment:
            CADENT_URL: http://cadent-dev:8083/graphite
            # GRAPHITE_STORAGE_DIR: /tmp/graphite/

        ports:
            - "0.0.0.0:8080:8080"

        volumes:
            - cadent-data:/data

    grafana:
        image:  grafana/grafana
        ports:
           - "0.0.0.0:3000:3000"

    cadent:
        build:
            context: .
            dockerfile: docker/cadent.docker

        ports:
            - "0.0.0.0:2003:2003"

    # this just puts the current land in a container and snoozes
    # you probably will need to
    # docker exec -ti $(docker ps | grep cadent-dev | cut -d" " -f1) bash
    cadent-dev:
        build:
            context: .
            dockerfile: docker/cadent.dev.docker

        volumes:
            - ./:/go/src
            - cadent-data:/data

        links:
            - graphite
        command: '/bin/bash -c "trap : TERM INT; sleep infinity & wait"'
        ports:
            - "0.0.0.0:2003:2003"


    #####
    ## External deps
    #####

    elasticsearch:
      image: elasticsearch:2.4
      ports:
          - "0.0.0.0:9200:9200"
          - "9300:9300"

    kibana:
      image: kibana:latest
      ports:
          - "0.0.0.0:5601:5601"
      links:
          - elasticsearch

    zookeeper:
      image: wurstmeister/zookeeper
      ports:
        - "2181:2181"

    kafka:
      image: wurstmeister/kafka
      ports:
        - "0.0.0.0:9092:9092"
      links:
        - zookeeper:zk
      environment:
        KAFKA_CREATE_TOPICS: "cadent:1:1"
        KAFKA_ADVERTISED_PORT: 9092
        KAFKA_PORT: 9092
        KAFKA_ADVERTISED_HOST_NAME: 0.0.0.0
        KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

    cassandra:
      image: cassandra
      ports:
        - "0.0.0.0:9042:9042"
        - "0.0.0.0:7199:7199"
        - "0.0.0.0:9160:9160"

    opscenter:
          image: abh1nav/opscenter:latest
          links:
            - cassandra
          ports:
            - "0.0.0.0:8888:8888"
