### pre-regex filters to push things around various backends
### if there are multiple backends or reject some things

[graphite-regex-map]
listen_server="graphite-proxy"   # which listener to sit in front of (must be in the main config)
default_backend="graphite-proxy"

    # another backend
    [[graphite-regex-map.map]]
    #what we're regexed from the input
    regex="""^servers.main.*"""
    backend="graphite-proxy"

    # anything that starts with the prefix
    [[graphite-regex-map.map]]
    prefix="""servers.main-"""
    backend="graphite-statsd"

    # Sub string type match
    [[graphite-regex-map.map]]
    substring=".badline."
    reject=true  # special "reject me" type

[statsd-regex-map]
listen_server="statsd-proxy" # which listener to sit in front of  (must be in the main config)
default_backend="statsd-proxy"  # failing a match go here

    [statsd-regex-map.accumulator]
    backend = "graphite-proxy"
    input_format = "statsd"
    output_format = "graphite"
    flush_time = "2s"


    [[statsd-regex-map.map]]
    substring="badline"
    reject=true  # special "reject me" type

    # another backend
    [[statsd-regex-map.map]]
    regex='^stats.timers..*'  #what we're regexed from the input
    backend="statsd-proxy"

    # anything that starts with the prefix (in lue of a more expesive regex)
    [[statsd-regex-map.map]]
    prefix="statdtest.here."
    backend="statsd-servers"
