### pre-regex filters to push things around various backends
### if there are multiple backends or reject some things

[graphite-regex-map]
listen_server="graphite-proxy"
default_backend="graphite-proxy"

    # another backend
    [[graphite-regex-map.map]]
    #what we're regexed from the input
    regex="""^servers.main.*"""
    backend="graphite-proxy"

    # anything that starts with the prefix (in lue of a more expesive regex)
    [[graphite-regex-map.map]]
    prefix="""servers.main-"""
    backend="graphite-statsd"

    [[graphite-regex-map.map]]
    regex="^servers.*"
    reject=true  # special "reject me" type

[statsd-regex-map]
default_backend="statsd-proxy"
listen_server="statsd-proxy"

    # another backend
    [[statsd-regex-map.map]]
    regex="""^stats.timers..*"""   #what we're regexed from the input
    backend="statsd-proxy"

    # anything that starts with the prefix (in lue of a more expesive regex)
    [[statsd-regex-map.map]]
    prefix="statdtest.here."
    backend="statsd-servers"

    [[statsd-regex-map.map]]
    regex="""^statdtest.house..*"""
    reject=true  # special "reject me" type
