##
##  Cassandra-Series ONLY writer
##
##  note the `backend = "BLACKHOLE"` below, this implys the Lines stop at the writer
##
##  cadent --config=graphite-config.toml --prereg=graphite-cassandra-series.toml
##
##

[graphite-proxy-map]
listen_server="graphite-proxy" # which listener to sit in front of  (must be in the main config)
default_backend="graphite-proxy"  # failing a match go here

    [graphite-proxy-map.accumulator]
    backend = "BLACKHOLE"
    input_format = "graphite"
    output_format = "graphite"
    random_ticker_start = false

    # aggregate bin counts
    accumulate_flush = "1s"
    times = ["1s:24h", "5s:72h", "1m:720h"]

    # cache objects to be shared (or not) across the writer backends
    [[graphite-proxy-map.accumulator.writer.caches]]
        name="gorilla"
        series_encoding="gorilla"
        bytes_per_metric=1024
        max_metrics=1024000  # for 1 million points @ 1024 b you'll need lots o ram


    # AND write things to the cassandra DB
    # cassandra api, metrics writer and path indexer
    [graphite-proxy-map.accumulator.writer.metrics]
        driver = "cassandra-log-triggered"
        dsn = "localhost"
        cache="gorilla"
        [graphite-proxy-map.accumulator.writer.metrics.options]
            port=9042
            keyspace="metric"
            metrics_table="metric_series"
            writer_index=1 # if you have multiple writers you'll need to have UNIQUE ids for them
            sniff=false # do this if you don't want the auto-detection of the cluster nodes (i.e. in a dev env as it can be slow)


    [graphite-proxy-map.accumulator.writer.indexer]
        driver = "cassandra"
        dsn = "localhost"
        [graphite-proxy-map.accumulator.writer.indexer.options]
            writes_per_second=100
            port=9042
            metrics_table="metric_series"
            keyspace="metric"
            path_table="path"
            segment_table="segment"
            sniff=false

    [graphite-proxy-map.accumulator.api]
        base_path = "/graphite/"
        listen = "0.0.0.0:8083"

        [graphite-proxy-map.accumulator.api.metrics]
            driver = "cassandra-log-triggered"
            dsn = "localhost"
            cache="gorilla"
            [graphite-proxy-map.accumulator.api.metrics.options]
                port=9042
                metrics_table="metric_series"
                keyspace="metric"
                path_table="path"
       		    segment_table="segment"
       		    writer_index=1


        [graphite-proxy-map.accumulator.api.indexer]
            driver = "cassandra"
            dsn = "localhost"
            [graphite-proxy-map.accumulator.api.indexer.options]
                port=9042
                metrics_table="metric_series"
                keyspace="metric"
                path_table="path"
                segment_table="segment"

    # Sub string type match
    [[graphite-proxy-map.map]]
        substring=".marvel"  # ignore elastic search marvel stuff
        reject=true