##
##  Cassandra-Series ONLY writer
##
##  note the `backend = "BLACKHOLE"` below, this implys the Lines stop at the writer
##
##  cadent --config=graphite-config.toml --prereg=graphite-cassandra-series.toml
##
##

[graphite-proxy-map]
listen_server="graphite-proxy" # which listener to sit in front of  (must be in the main config)
default_backend="graphite-proxy"  # failing a match go here

    [graphite-proxy-map.accumulator]
    backend = "BLACKHOLE"
    input_format = "graphite"
    output_format = "graphite"
    random_ticker_start = false

    # aggregate bin counts
    accumulate_flush = "5s"
    times = ["5s:1h", "1m:168h"]

    # cache objects to be shared (or not) across the writer backends
    [[graphite-proxy-map.accumulator.writer.caches]]
        name="gorilla"
        series_encoding="gorilla"
        bytes_per_metric=1024
        max_metrics=1024000  # for 1 million points @ 1024 b you'll need lots o ram
        # max_time_in_cache="2m" # force a cache flush for metrics in ram longer then this number
        # broadcast_length="128" # buffer channel for pushed overflow writes
        # overflow_method="drop" # if over bytes/maxmetrics for non-series writers, drop incoming
        # for non-series metrics, the typical behavior is to flush the highest counts first,
        # but that may mean lower counts never get written, this value "flips" the sorter at this % rate to
        # force the "smaller" ones to get written more often
        # low_fruit_rate= 0.25

    # AND write things to the cassandra DB
    # cassandra api, metrics writer and path indexer
    [graphite-proxy-map.accumulator.writer.metrics]
        driver = "cassandra"
        dsn = "127.0.0.1"
        cache="gorilla"
        [graphite-proxy-map.accumulator.writer.metrics.options]
            port=9042
            keyspace="metric"
            metrics_table="metric_series"
            write_queue_length=100
            writes_per_second=500


    [graphite-proxy-map.accumulator.writer.indexer]
        driver = "cassandra"
        dsn = "127.0.0.1"
        [graphite-proxy-map.accumulator.writer.indexer.options]
            writes_per_second=100
            port=9042
            keyspace="metric"
            path_table="path"
            segment_table="segment"

    [graphite-proxy-map.accumulator.api]
        base_path = "/graphite/"
        listen = "0.0.0.0:8083"

        [graphite-proxy-map.accumulator.api.metrics]
            driver = "cassandra"
            dsn = "127.0.0.1"
            cache="gorilla"
            [graphite-proxy-map.accumulator.api.metrics.options]
                port=9042
                metrics_table="metric_series"
                keyspace="metric"
                path_table="path"
       		    segment_table="segment"

        [graphite-proxy-map.accumulator.api.indexer]
            driver = "cassandra"
            dsn = "127.0.0.1"
            [graphite-proxy-map.accumulator.api.indexer.options]
                port=9042
                keyspace="metric"
                path_table="path"
                segment_table="segment"

    # Sub string type match
    [[graphite-proxy-map.map]]
        substring=".marvel"  # ignore elastic search marvel stuff
        reject=true