##
##  Mysql-Series ONLY writer
##
##  note the `backend = "BLACKHOLE"` below, this implys the Lines stop at the writer
##
##  Basically the same as cassandra blob writers
##


[graphite-proxy-map]
listen_server="graphite-proxy" # which listener to sit in front of  (must be in the main config)
default_backend="graphite-proxy"  # failing a match go here

    [graphite-proxy-map.accumulator]
    backend = "BLACKHOLE"
    input_format = "graphite"
    output_format = "graphite"
    random_ticker_start = false

    # aggregate bin counts
    accumulate_flush = "5s"
    times = ["5s:1h", "1m:168h"]

    # AND write things to the cassandra DB
    # cassandra api, metrics writer and path indexer
    [graphite-proxy-map.accumulator.writer.metrics]
        driver = "mysql"
        dsn = "root:@tcp(localhost:3306)/cadent"
        [graphite-proxy-map.accumulator.writer.metrics.options]
            cache_series_type="gorilla"
            cache_byte_size=4096
            cache_metric_size=1024000  # for 1 million points @ 4096 b you'll need lots o ram


    [graphite-proxy-map.accumulator.writer.indexer]
        driver = "mysql"
        dsn = "root:@tcp(localhost:3306)/cadent"
        [graphite-proxy-map.accumulator.writer.indexer.options]
        writes_per_second=200

    [graphite-proxy-map.accumulator.api]
        base_path = "/graphite/"
        listen = "0.0.0.0:8083"

            [graphite-proxy-map.accumulator.api.metrics]
                driver = "mysql"
                dsn = "root:@tcp(localhost:3306)/cadent"

            [graphite-proxy-map.accumulator.api.indexer]
                driver = "mysql"
                dsn = "root:@tcp(localhost:3306)/cadent"

    # Sub string type match
    [[graphite-proxy-map.map]]
        substring=".marvel"  # ignore elastic search marvel stuff
        reject=true