### pre-regex filters to push things around various backends
### if there are multiple backends or reject some things
## bind to the graphite input,
[graphite-cassandra]
listen_server="graphite-proxy"
default_backend="graphite-proxy"

    # accumulator and
    [graphite-cassandra.accumulator]
    backend = "graphite-gg-relay"  # loop back, the code will bypass the accumulator on the second pass
    input_format = "graphite"
    output_format = "graphite"

    # push out to writer aggregator collector and the backend every 10s
    # this should match the FIRST time in your times below
    accumulate_flush = "10s"

    # aggregate bin counts
    times = ["10s:168h", "1m:720h", "10m:21600h"]

    [graphite-cassandra.accumulator.writer.metrics]
        driver = "cassandra"
        dsn = "metrics-1-cassandra-db-integ.mfpaws.com,metrics-2-cassandra-db-integ.mfpaws.com,metrics-3-cassandra-db-integ.mfpaws.com"
        [graphite-cassandra.accumulator.writer.metrics.options]
            user="cassandra"
            pass="cassandra"
            port=9042
            numcons=50 # DB connection pool size
            timeout="30s" # DB timeout
            read_consistency="one"  # read consistency "one", "local_quorum" or "quorum"
            write_consistency="one"  # write consistency "one", "local_quorum" or "quorum" :: REALLY USE "ONE" HERE
            keyspace="metric"
            metrics_table="metric"
            path_table="path"
            segment_table="segment"


    [graphite-cassandra.accumulator.writer.indexer]
        driver = "cassandra"
        dsn = "metrics-1-cassandra-db-integ.mfpaws.com,metrics-2-cassandra-db-integ.mfpaws.com,metrics-3-cassandra-db-integ.mfpaws.com"
            [graphite-cassandra.accumulator.writer.indexer.options]
            user="cassandra"
            pass="cassandra"
            numcons=50

    [graphite-cassandra.accumulator.api]
    base_path = "/graphite/"
    listen = "0.0.0.0:8083"
        [graphite-cassandra.accumulator.api.metrics]
        driver = "cassandra"
        dsn = "metrics-1-cassandra-db-integ.mfpaws.com,metrics-2-cassandra-db-integ.mfpaws.com,metrics-3-cassandra-db-integ.mfpaws.com"
            [graphite-cassandra.accumulator.api.metrics.options]
            user="cassandra"
            pass="cassandra"

        [graphite-cassandra.accumulator.api.indexer]
        driver = "cassandra"
        dsn = "metrics-1-cassandra-db-integ.mfpaws.com,metrics-2-cassandra-db-integ.mfpaws.com,metrics-3-cassandra-db-integ.mfpaws.com"
            [graphite-cassandra.accumulator.api.indexer.options]
            user="cassandra"
            pass="cassandra"

    [[graphite-cassandra.map]]
    # Sub string type match
        substring=".marvel"  # ignore elastic search marvel stuff
        reject=true
