#!/bin/bash

source "$(dirname "${0}")/shared.env"

#assume if one is running they're all running
RUNNING="$(supervisorctl -c "${SUPERVISORD_CONF}" status consthash:consthash | grep RUNNING)"


if test "${RUNNING}z" != "z"
then
        exit 0
else
        exit 1
fi